# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-19 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ymac_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heritagesurvey',
            options={'managed': False, 'ordering': ('date_create',)},
        ),
        migrations.AlterModelOptions(
            name='siteuser',
            options={'managed': False, 'ordering': ('user_name',)},
        ),
    ]
