# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-12 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ymac_db', '0002_auto_20160512_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitedocument',
            options={'managed': True},
        ),
    ]
