# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-06-13 04:49
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('ymac_db', '0002_auto_20160613_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritagesurvey',
            name='consultants',
            field=models.ManyToManyField(blank=True, help_text='Consultants for survey', null=True,
                                         to='ymac_db.Consultant'),
        ),
        migrations.AddField(
            model_name='heritagesurvey',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='created_user', to='ymac_db.SiteUser'),
        ),
        migrations.AddField(
            model_name='heritagesurvey',
            name='data_source',
            field=models.ManyToManyField(blank=True, help_text='Any comments or data relating to the data', null=True,
                                         to='ymac_db.SurveyCleaning'),
        ),
        migrations.AddField(
            model_name='heritagesurvey',
            name='data_status',
            field=models.ForeignKey(blank=True,
                                    help_text='For current spatial data is it proposed or after survey completion (Actual)',
                                    null=True, on_delete=django.db.models.deletion.CASCADE, to='ymac_db.SurveyStatus'),
        ),
        migrations.AddField(
            model_name='heritagesurvey',
            name='mod_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='mod_user', to='ymac_db.SiteUser'),
        ),
        migrations.AddField(
            model_name='heritagesurvey',
            name='proponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ymac_db.Proponent'),
        ),
        migrations.AddField(
            model_name='heritagesurvey',
            name='proponent_codes',
            field=models.ManyToManyField(blank=True,
                                         help_text='Any proponent codes relating to the survey i.e RIO Area Codes AR-00-00000',
                                         null=True, to='ymac_db.SurveyProponentCode'),
        ),
        migrations.AddField(
            model_name='heritagesurvey',
            name='sampling_meth',
            field=models.ForeignKey(blank=True, db_column='sampling_meth', default=6, null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='ymac_db.SampleMethodology'),
        ),
        migrations.AddField(
            model_name='heritagesurvey',
            name='survey_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ymac_db.SurveyGroup'),
        ),
        migrations.AddField(
            model_name='heritagesurvey',
            name='survey_methodologies',
            field=models.ManyToManyField(blank=True, null=True, to='ymac_db.SurveyMethodology'),
        ),
        migrations.AddField(
            model_name='heritagesurvey',
            name='survey_trip',
            field=models.ForeignKey(default=2017, help_text='Trip and related Trip information',
                                    on_delete=django.db.models.deletion.CASCADE, to='ymac_db.HeritageSurveyTrip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heritagesurvey',
            name='survey_type',
            field=models.ForeignKey(blank=True, db_column='survey_type', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='ymac_db.SurveyType'),
        ),
        migrations.AlterField(
            model_name='heritagesurvey',
            name='data_qa',
            field=models.BooleanField(default=False, help_text='Has Actual data been checked by Spatial Team'),
        ),
        migrations.AlterField(
            model_name='heritagesurvey',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4283),
        ),
        migrations.AlterField(
            model_name='heritagesurvey',
            name='project_name',
            field=models.TextField(blank=True, help_text='Internal or Survey Project Name', null=True),
        ),
        migrations.AlterField(
            model_name='heritagesurvey',
            name='project_status',
            field=models.CharField(blank=True, choices=[('On Hold', 'On Hold'), ('In Progress', 'In Progress'),
                                                        ('Date Set', 'Date Set'), ('Proposed Date', 'Proposed Date'),
                                                        ('Cancelled', 'Cancelled'), ('Completed', 'Completed'),
                                                        ('Postponed', 'Postponed'),
                                                        ('Heritage Notice Recd', 'Heritage Notice Recd'),
                                                        ('PA Received', 'PA Received'),
                                                        ('PA Sent to Proponent', 'PA Sent to Proponent'),
                                                        ('Draft Report Received', 'Draft Report Received'),
                                                        ('Final Report Received', 'Final Report Received'),
                                                        ('Field Work Completed', 'Field Work Completed')], default=3,
                                   max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='heritagesurvey',
            name='survey_description',
            field=models.TextField(blank=True, help_text='Description of the proposed or actual survey', null=True),
        ),
        migrations.AlterField(
            model_name='heritagesurvey',
            name='survey_note',
            field=models.TextField(blank=True, help_text='Additional Survey notes', null=True),
        ),
    ]
