# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-12 09:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ymac_db', '0003_auto_20160512_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedocument',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ymac_db.Site'),
        ),
        migrations.AlterField(
            model_name='sitedocument',
            name='document_type',
            field=models.CharField(
                choices=[('Image', 'Image'), ('Audio', 'Audio'), ('Video', 'Video'), ('Document', 'Document'),
                         ('Map', 'Map'), ('Other', 'Other')], max_length=15),
        ),
    ]
