# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-06-13 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('ymac_db', '0003_auto_20160613_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritagesurvey',
            name='sampling_conf',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ymac_db.SamplingConfidence'),
        ),
    ]
