# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-12 09:03
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ymac_db', '0004_auto_20160512_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedocument',
            name='site',
            field=models.ForeignKey(blank=True, db_column='site_id', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='ymac_db.Site'),
        ),
    ]
