# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-13 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ymac_db', '0006_researchsite_family_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchsite',
            name='mapsheet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
