# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-16 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('ymac_db', '0007_researchsite_mapsheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_description', models.CharField(
                    choices=[('Artefacts / Scatter', 'Artefacts / Scatter'), ('Birthplace', 'Birthplace'),
                             ('Ceremonial', 'Ceremonial'), ('Engravings', 'Engravings'),
                             ('Grinding Groove', 'Grinding Groove'), ('Gnamma Hole', 'Gnamma Hole'),
                             ('Mythological', 'Mythological')], max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='heritagesite',
            name='site_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ymac_db.SiteDescriptions'),
        ),
    ]
