# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-16 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('ymac_db', '0008_add_site_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.TextField()),
                ('organisation_website', models.TextField()),
                ('organisation_phone', models.CharField(max_length=16)),
                ('organisation_contact', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('employee', models.NullBooleanField()),
                ('email', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                (
                'capture_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ymac_db.CaptureOrg')),
            ],
        ),
    ]
