# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-16 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('ymac_db', '0009_add_site_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captureorg',
            name='organisation_contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='captureorg',
            name='organisation_phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='captureorg',
            name='organisation_website',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='capture_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ymac_db.CaptureOrg'),
        ),
    ]
