# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-16 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ymac_db', '0010_auto_20160516_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='first_name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='username',
        ),
    ]
