# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-16 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ymac_db', '0012_auto_20160516_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveystatus',
            options={'managed': True},
        ),
    ]
