# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-16 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ymac_db', '0013_auto_20160516_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heritagesurvey',
            old_name='heriage_sites',
            new_name='heritage_sites',
        ),
    ]
