# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-16 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ymac_db', '0014_auto_20160516_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritagesite',
            name='documents',
            field=models.ManyToManyField(db_column='site_id', related_name='heritagedocuments',
                                         to='ymac_db.SiteDocument'),
        ),
        migrations.AddField(
            model_name='heritagesite',
            name='heritage_surveys',
            field=models.ManyToManyField(db_column='site_id', related_name='heritagesurveys',
                                         to='ymac_db.HeritageSurvey'),
        ),
        migrations.AddField(
            model_name='researchsite',
            name='documents',
            field=models.ManyToManyField(db_column='site_id', related_name='researchdocuments',
                                         to='ymac_db.SiteDocument'),
        ),
        migrations.AlterField(
            model_name='surveystatus',
            name='survey_status_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
