# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-17 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ymac_db', '0016_auto_20160517_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritagesite',
            name='status',
            field=models.TextField(blank=True, choices=[('Protected', 'Protected'), ('Cleared', 'Cleared'),
                                                        ('Restricted', 'Restricted'), ('Provisional', 'Provisional'),
                                                        ('Stored Data', 'Stored Data')], max_length=15, null=True),
        ),
    ]
